"""Client and roles changed

Revision ID: 269ac20de6dd
Revises: 5ef06d93b763
Create Date: 2023-01-06 12:37:44.097161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '269ac20de6dd'
down_revision = '5ef06d93b763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.String(length=25), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('client_description', sa.String(length=255), nullable=True),
    sa.Column('redirect_url', sa.String(length=1000), nullable=False),
    sa.Column('logout_redirect_url', sa.String(length=1000), nullable=True),
    sa.Column('web_origins', sa.String(length=1000), nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['username'], ['users.username'], )
    )
    op.drop_table('user_scopes')
    op.drop_table('scopes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scopes',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('scope', mysql.VARCHAR(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('user_scopes',
    sa.Column('username', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('scope_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['scope_id'], ['scopes.id'], name='user_scopes_ibfk_1'),
    sa.ForeignKeyConstraint(['username'], ['users.username'], name='user_scopes_ibfk_2'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user_roles')
    op.drop_table('roles')
    op.drop_table('clients')
    # ### end Alembic commands ###
